### ISSUE TITLE
Evebox agent: configuration property "input" not found

### ISSUE THREAD

**Issue by uvelokk** [jasonish/evebox#134]
OS: Debian 10
Evebox version: 0.12.0-dev (rev da97d35); x86_64-unknown-linux-musl (Debian package)

Problem: Evebox agent gets panicked: configuration property "input" not found

```
$ sudo RUST_BACKTRACE=full /usr/bin/evebox agent
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration property "input" not found', /src/src/agent/main.rs:46:30
stack backtrace:
   0:           0x916c5d - backtrace::backtrace::libunwind::trace::h054f55e3dc06bc5e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:           0x916c5d - backtrace::backtrace::trace_unsynchronized::h1186ac2475a6fb30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:           0x916c5d - std::sys_common::backtrace::_print_fmt::h461344b5d95acdca
                               at src/libstd/sys_common/backtrace.rs:78
   3:           0x916c5d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6282cf42b714e880
                               at src/libstd/sys_common/backtrace.rs:59
   4:           0x51182c - core::fmt::write::hc2a3a9db73907d34
                               at src/libcore/fmt/mod.rs:1063
   5:           0x9163a1 - std::io::Write::write_fmt::h99f78802c17ed488
                               at src/libstd/io/mod.rs:1426
   6:           0x915f05 - std::sys_common::backtrace::_print::h81d44cbe95d725dc
                               at src/libstd/sys_common/backtrace.rs:62
   7:           0x915f05 - std::sys_common::backtrace::print::h0fc8ade31453f483
                               at src/libstd/sys_common/backtrace.rs:49
   8:           0x915f05 - std::panicking::default_hook::{{closure}}::hbd2f47050b7511e4
                               at src/libstd/panicking.rs:204
   9:           0x91549a - std::panicking::default_hook::hc7cc8bcc86ad3d5f
                               at src/libstd/panicking.rs:224
  10:           0x91549a - std::panicking::rust_panic_with_hook::hc3b9a5b3f9266bae
                               at src/libstd/panicking.rs:470
  11:           0x915038 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:           0x50f330 - core::panicking::panic_fmt::h9eaff8afd9ffd7d8
                               at src/libcore/panicking.rs:85
  13:           0x515ac2 - core::option::expect_none_failed::hcbd323a6f68cb13c
                               at src/libcore/option.rs:1211
  14:           0x462be4 - evebox::_main::{{closure}}::hbe483cb2d840e560
  15:           0x5a908e - std::thread::local::LocalKey<T>::with::h3ad5caf87b68facb
  16:           0x468ab1 - evebox::main::h1fbd4b1ed321eeb0
  17:           0x55b5d3 - std::rt::lang_start::{{closure}}::hd3dd49992e713931
  18:           0x46a5bd - main
```

Uncommented lines from `/etc/evebox/agent.yaml`:
```
server:
  url: http://xx.xx.xx.xx:5636
bookmark-directory: "/var/lib/evebox"
disable-certificate-check: true
input:
  filename: "/var/log/suricata/eve.json"
  custom-fields:
```

**Comment by jasonish** [comment]
Please update, it should be fixed now.

If not, you might want to look at using the stable version.  The development version is going through some large changes at the moment.
