### ISSUE TITLE
No data with ES 5.5 if Elasticsearch URL ends with /

### ISSUE THREAD

**Issue by regit** [jasonish/evebox#55]
I've faced this issue when connecting a Evebox 0.8.0 to an elascticsearch. By passing the -e flag to evebox and finishing the value with a /, we get no data in Evebox. Removing the / fixes the issue.

The explanation is quite "fun". If URL ends with a / then requests send by Evebox are:
```
http://elasticsearch:9200//logstash-*/_search
```
Elasticsearch (at least 5.5.0) is seeing this as a search request on any index for type `logstash-*`. Consequence is that it fails to find any data.

A simple fix should be to remove the `/` if present at the end of the Elasticsearch URL.

**Comment by regit** [comment]
And here is Elasticsearch traceback for the one who loves concise error messages:
```
[2017-07-12T17:15:51,685][DEBUG][o.e.a.s.TransportSearchAction] [es1-es1] [.kibana][0], node[FM0vxqeRS_C5g7YmsOcD-Q], [P], s[STARTED], a[id=lXOHwYGeRjaqaTIxNlrs3w]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[logstash-*], routing='null', preference='null', requestCache=null, scroll=null, source={
  "query" : {
    "bool" : {
      "filter" : [
        {
          "exists" : {
            "field" : "event_type",
            "boost" : 1.0
          }
        },
        {
          "term" : {
            "event_type" : {
              "value" : "alert",
              "boost" : 1.0
            }
          }
        }
      ],
      "disable_coord" : false,
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "sort" : [
    {
      "@timestamp" : {
        "order" : "desc"
      }
    }
  ],
  "aggregations" : {
    "signatures" : {
      "terms" : {
        "field" : "alert.signature_id",
        "size" : 10000,
        "min_doc_count" : 1,
        "shard_min_doc_count" : 0,
        "show_term_doc_count_error" : false,
        "order" : [
          {
            "_count" : "desc"
          },
          {
            "_term" : "asc"
          }
        ]
      },
      "aggregations" : {
        "sources" : {
          "terms" : {
            "field" : "src_ip",
            "size" : 10000,
            "min_doc_count" : 1,
            "shard_min_doc_count" : 0,
            "show_term_doc_count_error" : false,
            "order" : [
              {
                "_count" : "desc"
              },
              {
                "_term" : "asc"
              }
            ]
          },
          "aggregations" : {
            "destinations" : {
              "terms" : {
                "field" : "dest_ip",
                "size" : 10000,
                "min_doc_count" : 1,
                "shard_min_doc_count" : 0,
                "show_term_doc_count_error" : false,
                "order" : [
                  {
                    "_count" : "desc"
                  },
                  {
                    "_term" : "asc"
                  }
                ]
              },
              "aggregations" : {
                "escalated" : {
                  "filter" : {
                    "term" : {
                      "tags" : {
                        "value" : "escalated",
                        "boost" : 1.0
                      }
                    }
                  }
                },
                "newest" : {
                  "top_hits" : {
                    "from" : 0,
                    "size" : 1,
                    "version" : false,
                    "explain" : false,
                    "sort" : [
                      {
                        "@timestamp" : {
                          "order" : "desc"
                        }
                      }
                    ]
                  }
                },
                "oldest" : {
                  "top_hits" : {
                    "from" : 0,
                    "size" : 1,
                    "version" : false,
                    "explain" : false,
                    "sort" : [
                      {
                        "@timestamp" : {
                          "order" : "asc"
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [es1-es1][192.168.56.102:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [@timestamp] in order to sort on
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:262) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:630) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:481) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:253) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:330) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:327) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by jasonish** [comment]
Should be fixed now. Available in the latest development builds.

Thanks!
