### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference on FreeBSD when reading eve.json

### ISSUE THREAD

**Issue by torokp** [jasonish/evebox#57]
From version 0.8 I got the following error, when evebox tries to read the eve.json.
The system is FreeBSD 11.1

```
[root@box /opt/evebox]# ./evebox esimport -v -e http://localhost:9200 /var/log/suricata/eve.json
2017-08-14 15:16:00 (esimport.go:128) <Info> -- Setting log level to debug
2017-08-14 15:16:00 (esimport.go:181) <Info> -- Connected to Elastic Search v5.3.0 (cluster:elasticsearch; name: zWQJHOb)
2017-08-14 15:16:00 (esimport.go:193) <Info> -- Template evebox exists, will not create.
2017-08-14 15:16:00 (rulemap.go:54) <Warning> -- Failed to initialize file watcher, rules won't be automatically reloaded: function not implemented
2017-08-14 15:16:00 (rulemap.go:108) <Info> -- Loaded 0 rules
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x846ffa]

goroutine 21 [running]:
github.com/jasonish/evebox/rules.(*RuleMap).watchFiles(0xc421206040)
        /home/travis/gopath/src/github.com/jasonish/evebox/rules/rulemap.go:79 +0x9a
created by github.com/jasonish/evebox/rules.NewRuleMap
        /home/travis/gopath/src/github.com/jasonish/evebox/rules/rulemap.go:65 +0x11d
```

With 0.7 it works correctly.

**Comment by jasonish** [comment]
Not fixing. Appears to be an issue when running the Linux binary on FreeBSD.
